#!/bin/bash
sudo apt-get update
sudo apt-get install -y build-dep vim-gnome ruby-dev
git clone https://github.com/vim/vim ~/vim
cd ~/vim/src
make distclean
./configure --with-features=huge
make
sudo make install
vim --version
cd ~/.vim
cp .vimrc ~/
git submodule init
git submodule update
echo "Finished"
