#!/bin/bash
sudo apt-get update
sudo apt-get install -y vim-gnome ruby-dev
sudo apt-get install -y libncurses5-dev libgnome2-dev libgnomeui-dev \
  libgtk2.0-dev libatk1.0-dev libbonoboui2-dev \
  libcairo2-dev libx11-dev libxpm-dev libxt-dev
git clone https://github.com/vim/vim ~/vim
cd ~/vim/src
make distclean
./configure --with-features=huge
make
sudo make install
vim --version
cd ~/.vim
cp .vimrc ~/
git submodule init
git submodule update
echo "Finished"
